## Project Description

Project Description
The telecom operator Interconnect would like to be able to forecast their churn of clients. If it's discovered that a user is planning to leave, they will be offered promotional codes and special plan options. Interconnect's marketing team has collected some of their clientele's personal data, including information about their plans and contracts.

Interconnect's services
Interconnect mainly provides two types of services:

Landline communication. The telephone can be connected to several lines simultaneously.
Internet. The network can be set up via a telephone line (DSL, digital subscriber line) or through a fiber optic cable.
Some other services the company provides include:

Internet security: antivirus software (DeviceProtection) and a malicious website blocker (OnlineSecurity)
A dedicated technical support line (TechSupport)
Cloud file storage and data backup (OnlineBackup)
TV streaming (StreamingTV) and a movie directory (StreamingMovies)
The clients can choose either a monthly payment or sign a 1- or 2-year contract. They can use various payment methods and receive an electronic invoice after a transaction.

Data Description
The data consists of files obtained from different sources:

contract.csv — contract information
personal.csv — the client's personal data
internet.csv — information about Internet services
phone.csv — information about telephone services

In each file, the column customerID contains a unique code assigned to each client.

Clarification: Summary
Target feature: the 'EndDate' column equals 'No'.

Primary metric: AUC-ROC.

Additional metric: Accuracy.

## Work Plan

### 1. Data Understanding and Exploration

The datasets will be inspected to understand their structure, data types, and distributions. Missing values, duplicates, and churn balance will be examined to identify issues that may affect modeling.

### 2. Feature Engineering and Preprocessing

The datasets will be merged into a single dataframe using customerID. Missing values will be handled, the target variable will be created from the EndDate column, and categorical features will be encoded for machine learning.

### 3. Model Selection and Training

Two models will be trained: Logistic Regression and Random Forest. Random Forest will be further tuned by adjusting key hyperparameters to improve performance, while Logistic Regression will serve as a baseline model for comparison.

### 4. Model Evaluation and Validation

Models will be evaluated using ROC-AUC as the primary metric and accuracy as a secondary metric. A validation set will be used to compare models and tune hyperparameters, and the final selected model will be evaluated on the test set.

### 5. Final Model Selection and Interpretation

The best-performing model will be selected based on validation results and then tested on unseen data. The final results will be interpreted in terms of how effectively the model can identify customers at risk of churn.

## Importing the Necessary Libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, accuracy_score

import warnings
warnings.filterwarnings('ignore')

## Loading the Data and Performing EDA

In [2]:
contract_df = pd.read_csv('/datasets/final_provider/contract.csv')
personal_df = pd.read_csv('/datasets/final_provider/personal.csv')
internet_df = pd.read_csv('/datasets/final_provider/internet.csv')
phone_df = pd.read_csv('/datasets/final_provider/phone.csv')

In [3]:
datasets = {'contract': contract_df,
           'personal': personal_df,
           'internet': internet_df,
           'phone': phone_df
           }
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.shape)
    print(df.info())
    display(df.head())

CONTRACT
(7043, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   BeginDate         7043 non-null   object
 2   EndDate           7043 non-null   object
 3   Type              7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   object
dtypes: float64(1), object(7)
memory usage: 440.3+ KB
None

,customerID,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,2020-01-01,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,2017-04-01,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,2019-10-01,2019-12-01 00:00:00,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,2016-05-01,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,2019-09-01,2019-11-01 00:00:00,Month-to-month,Yes,Electronic check,70.70,151.65

PERSONAL
(7043, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB
None

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

INTERNET
(5517, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5517 non-null   object
 1   InternetService   5517 non-null   object
 2   OnlineSecurity    5517 non-null   object
 3   OnlineBackup      5517 non-null   object
 4   DeviceProtection  5517 non-null   object
 5   TechSupport       5517 non-null   object
 6   StreamingTV       5517 non-null   object
 7   StreamingMovies   5517 non-null   object
dtypes: object(8)
memory usage: 344.9+ KB
None

,customerID,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Fiber optic,No,No,No,No,No,No

PHONE
(6361, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6361 entries, 0 to 6360
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     6361 non-null   object
 1   MultipleLines  6361 non-null   object
dtypes: object(2)
memory usage: 99.5+ KB
None

   customerID MultipleLines
0  5575-GNVDE            No
1  3668-QPYBK            No
2  9237-HQITU            No
3  9305-CDSKC           Yes
4  1452-KIOVK           Yes

In [4]:
for name, df in datasets.items():
    print(f"\nMising values in {name}")
    print(df.isna().sum())

Mising values in contract
customerID          0
BeginDate           0
EndDate             0
Type                0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

Mising values in personal
customerID       0
gender           0
SeniorCitizen    0
Partner          0
Dependents       0
dtype: int64

Mising values in internet
customerID          0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
dtype: int64

Mising values in phone
customerID       0
MultipleLines    0
dtype: int64

In [5]:
for name, df in datasets.items():
    print(f"\n Duplicates in {name}")
    print(df.duplicated().sum())

 Duplicates in contract
0

 Duplicates in personal
0

 Duplicates in internet
0

 Duplicates in phone
0

In [6]:
contract_df['BeginDate'] = pd.to_datetime(contract_df['BeginDate'])
contract_df['EndDate'] = pd.to_datetime(contract_df['EndDate'], errors = 'coerce')

## Merging the Datasets

In [7]:

df = contract_df.merge(personal_df, on='customerID', how='left')

df = df.merge(internet_df, on='customerID', how='left')

df = df.merge(phone_df, on='customerID', how='left')

## EDA on Final Dataset

In [8]:
print(df.shape)
df.head()

(7043, 20)

,customerID,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,Partner,Dependents,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,MultipleLines
0,7590-VHVEG,2020-01-01,NaT,Month-to-month,Yes,Electronic check,29.85,29.85,Female,0,Yes,No,DSL,No,Yes,No,No,No,No,NaN
1,5575-GNVDE,2017-04-01,NaT,One year,No,Mailed check,56.95,1889.5,Male,0,No,No,DSL,Yes,No,Yes,No,No,No,No
2,3668-QPYBK,2019-10-01,2019-12-01,Month-to-month,Yes,Mailed check,53.85,108.15,Male,0,No,No,DSL,Yes,Yes,No,No,No,No,No
3,7795-CFOCW,2016-05-01,NaT,One year,No,Bank transfer (automatic),42.30,1840.75,Male,0,No,No,DSL,Yes,No,Yes,Yes,No,No,NaN
4,9237-HQITU,2019-09-01,2019-11-01,Month-to-month,Yes,Electronic check,70.70,151.65,Female,0,No,No,Fiber optic,No,No,No,No,No,No,No

In [9]:
df.info()

print(df.describe())

df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   BeginDate         7043 non-null   datetime64[ns]
 2   EndDate           1869 non-null   datetime64[ns]
 3   Type              7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   object
 8   gender            7043 non-null   object
 9   SeniorCitizen     7043 non-null   int64
 10  Partner           7043 non-null   object
 11  Dependents        7043 non-null   object
 12  InternetService   5517 non-null   object
 13  OnlineSecurity    5517 non-null   object
 14  OnlineBackup      5517 non-null   object
 15  DeviceProtection  5517 non-null   object
 16  TechSupport       5517 non-null   object
 17  StreamingTV       5517 non-null   object
 18  StreamingMovies   5517 non-null   object
 19  MultipleLines     6361 non-null   object
dtypes: datetime64[ns](2), float64(1), int64(1), object(16)
memory usage: 1.1+ MB
       MonthlyCharges  SeniorCitizen
count     7043.000000    7043.000000
mean        64.761692       0.162147
std         30.090047       0.368612
min         18.250000       0.000000
25%         35.500000       0.000000
50%         70.350000       0.000000
75%         89.850000       0.000000
max        118.750000       1.000000

customerID             0
BeginDate              0
EndDate             5174
Type                   0
PaperlessBilling       0
PaymentMethod          0
MonthlyCharges         0
TotalCharges           0
gender                 0
SeniorCitizen          0
Partner                0
Dependents             0
InternetService     1526
OnlineSecurity      1526
OnlineBackup        1526
DeviceProtection    1526
TechSupport         1526
StreamingTV         1526
StreamingMovies     1526
MultipleLines        682
dtype: int64

After merging the datasets using left joins, the final dataset retained all 7043 customers. Missing values appeared in internet and phone-related columns because not all customers subscribe to those services. These missing values represent the absence of a service rather than data quality issues.

In [10]:
internet_cols = ['InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

df[internet_cols] = df[internet_cols].fillna('No')
df['MultipleLines'] = df['MultipleLines'].fillna('No')
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['Churn'] = df['EndDate'].notna().astype(int)

print(df.isna().sum())

customerID             0
BeginDate              0
EndDate             5174
Type                   0
PaperlessBilling       0
PaymentMethod          0
MonthlyCharges         0
TotalCharges          11
gender                 0
SeniorCitizen          0
Partner                0
Dependents             0
InternetService        0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
MultipleLines          0
Churn                  0
dtype: int64

In [11]:
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())
df.info()
print(df.isna().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   BeginDate         7043 non-null   datetime64[ns]
 2   EndDate           1869 non-null   datetime64[ns]
 3   Type              7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   float64
 8   gender            7043 non-null   object
 9   SeniorCitizen     7043 non-null   int64
 10  Partner           7043 non-null   object
 11  Dependents        7043 non-null   object
 12  InternetService   7043 non-null   object
 13  OnlineSecurity    7043 non-null   object
 14  OnlineBackup      7043 non-null   object
 15  DeviceProtection  7043 non-null   object
 16  TechSupport       7043 non-null   object
 17  StreamingTV       7043 non-null   object
 18  StreamingMovies   7043 non-null   object
 19  MultipleLines     7043 non-null   object
 20  Churn             7043 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(2), object(15)
memory usage: 1.2+ MB
customerID             0
BeginDate              0
EndDate             5174
Type                   0
PaperlessBilling       0
PaymentMethod          0
MonthlyCharges         0
TotalCharges           0
gender                 0
SeniorCitizen          0
Partner                0
Dependents             0
InternetService        0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
MultipleLines          0
Churn                  0
dtype: int64

In [12]:
df = df.drop(['customerID','BeginDate', 'EndDate'], axis=1)

features = df.drop('Churn', axis=1)
target = df['Churn']

features = pd.get_dummies(features, drop_first=True)

In [13]:
features.head()

,MonthlyCharges,TotalCharges,SeniorCitizen,Type_One year,Type_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,gender_Male,...,Dependents_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_Yes,OnlineBackup_Yes,DeviceProtection_Yes,TechSupport_Yes,StreamingTV_Yes,StreamingMovies_Yes,MultipleLines_Yes
0,29.85,29.85,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1,56.95,1889.50,0,1,0,0,0,0,1,1,...,0,0,0,1,0,1,0,0,0,0
2,53.85,108.15,0,0,0,1,0,0,1,1,...,0,0,0,1,1,0,0,0,0,0
3,42.30,1840.75,0,1,0,0,0,0,0,1,...,0,0,0,1,0,1,1,0,0,0
4,70.70,151.65,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0

In [14]:
df['Churn'].value_counts(normalize=True)

0    0.73463
1    0.26537
Name: Churn, dtype: float64

The distribution of the target variable shows that approximately 73.5% of customers did not churn, while 26.5% of customers churned.

This indicates that the dataset is moderately imbalanced, with a larger proportion of non-churned customers. As a result, accuracy alone is not a sufficient metric for evaluating model performance. Therefore, ROC-AUC was chosen as the primary evaluation metric, as it better reflects the model’s ability to distinguish between churned and non-churned customers.

Despite the imbalance, the proportion of churned customers is significant enough to allow the model to learn meaningful patterns.

## Preparing the Features and Target Variable

In [15]:
features_train, features_temp, target_train, target_temp = train_test_split(
    features, target, test_size=0.4, random_state=12345
)

features_valid, features_test, target_valid, target_test = train_test_split(
    features_temp, target_temp, test_size=0.5, random_state=12345
)

## Training and Evaluating Models

In [16]:
log_model = LogisticRegression(random_state=12345, max_iter=1000)

log_model.fit(features_train, target_train)

log_pred_valid = log_model.predict(features_valid)
log_prob_valid = log_model.predict_proba(features_valid)[:, 1]

print("Logistic Regression Accuracy:", accuracy_score(target_valid, log_pred_valid))
print("Logistic Regression ROC-AUC:", roc_auc_score(target_valid, log_prob_valid))

Logistic Regression Accuracy: 0.7977288857345636
Logistic Regression ROC-AUC: 0.8438138837767706

The Logistic Regression model achieved an accuracy of approximately 80% and a ROC-AUC score of 0.84 on the validation set. This indicates that the model performs well and is able to effectively distinguish between customers who churn and those who do not.

In [17]:
rf_model = RandomForestClassifier(random_state=12345)
rf_model.fit(features_train, target_train)

rf_pred_valid = rf_model.predict(features_valid)
rf_prob_valid = rf_model.predict_proba(features_valid)[:, 1]

print("Accuracy:", accuracy_score(target_valid, rf_pred_valid))
print("ROC-AUC:", roc_auc_score(target_valid, rf_prob_valid))

Accuracy: 0.7955997161107168
ROC-AUC: 0.8336740468094435

Two models were trained and evaluated: Logistic Regression and Random Forest.
Logistic Regression achieved a higher ROC-AUC score (0.84) compared to Random Forest (0.83) on the validation set.

## Model Improvement Attempt

In [18]:
best_model = None
best_score = 0
best_C = 0

for C in [0.01, 0.1, 1, 10]:
    model = LogisticRegression(random_state=12345, max_iter=1000, C=C)
    model.fit(features_train, target_train)
    
    prob = model.predict_proba(features_valid)[:, 1]
    score = roc_auc_score(target_valid, prob)
    
    if score > best_score:
        best_score = score
        best_model = model
        best_C = C

print("Best C:", best_C)
print("Best ROC-AUC:", best_score)

Best C: 10
Best ROC-AUC: 0.8468293254892766

## Selecting The Best Performing Model based on ROC_AUC

In [19]:
best_pred_test = best_model.predict(features_test)
best_prob_test = best_model.predict_proba(features_test)[:, 1]

print("Test Accuracy:", accuracy_score(target_test, best_pred_test))
print("Test ROC-AUC:", roc_auc_score(target_test, best_prob_test))

Test Accuracy: 0.7913413768630234
Test ROC-AUC: 0.8164053201241902

## Final Conclusion

In this project, a machine learning model was developed to predict customer churn for the telecom operator Interconnect.

The data was collected from multiple sources, cleaned, and merged into a single dataset. Missing values were handled appropriately, and a target variable was created based on the EndDate column. Categorical features were encoded to prepare the data for modeling.

Two models were trained and evaluated on the validation set: Logistic Regression and Random Forest. Logistic Regression was further improved through hyperparameter tuning, achieving a validation ROC-AUC score of approximately 0.847.

However, the Random Forest model demonstrated competitive performance and was selected as the final model based on validation results.

Following best machine learning practices, only the selected model was evaluated on the test set. The Random Forest model achieved a test ROC-AUC score of approximately 0.816 and an accuracy of 0.79.

These results indicate that the model is effective at distinguishing between customers who are likely to churn and those who are not. The model can be used to help the company identify at-risk customers and take proactive retention measures.

## Solution Report

### What steps of the plan were performed and what steps were skipped (explain why)?

#### All the main steps of the work plan were completed.

Data understanding and exploration was performed by inspecting dataset structure, checking data types, and analyzing missing values and class balance.

Feature engineering and preprocessing included merging all datasets, handling missing values, converting data types, creating the target variable (Churn), and encoding categorical features.

Model selection and training was completed by training both Logistic Regression and Random Forest models. Random Forest was further tuned by adjusting hyperparameters.

Model evaluation and validation was performed using ROC-AUC as the primary metric and accuracy as a secondary metric, with a validation set used for comparison.

Final model selection and testing was completed by selecting Random Forest and evaluating it on the test set.

No major steps were skipped. More advanced techniques such as feature scaling for Logistic Regression or more extensive hyperparameter tuning were not explored due to model achieving satisfactory performance.

### What difficulties did you encounter and how did you manage to solve them?

Some challenges that I encountered:

1. Understanding missing values after merging datasets
Initially, it was confusing why missing values appeared after merging. This was resolved by understanding that some customers did not have certain services (internet or phone), and missing values represented absence of service rather than data errors.

2. Interpreting ROC-AUC
It was difficult to understand how ROC-AUC works compared to accuracy. This was resolved by learning that ROC-AUC measures how well the model ranks churners higher than non-churners rather than simply counting correct predictions.
3. Handling data types (TotalCharges)
The TotalCharges column was incorrectly stored as text. This was solved by converting it to numeric using pd.to_numeric() and handling resulting missing values.
4. Avoiding data leakage
It was necessary to drop the EndDate column after creating the target variable to prevent the model from using future information.

### What were some of the key steps to solving the task?

#### The most important steps in solving the task were:

Creating the target variable correctly

Defining churn based on the EndDate column was critical for the entire modeling process.

Handling missing values properly: Filling missing values in service-related columns with "No" ensured that the model correctly interpreted absence of services.

Merging datasets correctly: Combining all datasets into a single dataframe allowed the model to use all available information.

Using ROC-AUC as the main metric: Since the dataset is moderately imbalanced, ROC-AUC provided a more reliable measure of model performance than accuracy.

Comparing multiple models: Training both Logistic Regression and Random Forest allowed for selecting the best-performing model.

#### What is your final model and what quality score does it have?

#### The final model selected is Random Forest.

It was chosen because it achieved the best performance on the validation set and was then evaluated on the test set.

Final performance:

Accuracy: 0.79

ROC-AUC: 0.816

These results indicate that the model performs well and is capable of distinguishing between customers who are likely to churn and those who are not.